Feature/tile
mits-gossau/web-components-toolbox-klubschule pull request #1
Opened 2023-11-22 09:30 UTC by MrBuggy

2023-12-15 06:44 UTC, Weedshaker requested changes
Please, correct the few commented places, else it looks fine.

2023-12-15 06:44 UTC, Weedshaker commented on src/es/components/molecules/tile/Tile.js
> +    this.modifier = this.getAttribute('modifier') || '';
modifier is never used

2023-12-15 06:44 UTC, Weedshaker commented on src/es/components/organisms/tileList/TileList.js
> +  fetchTemplate () {
this function is useless and can be removed.

2024-01-17 13:56 UTC, Weedshaker approved these changes
phone pair approving

2024-01-17 16:46 UTC, Weedshaker approved these changes

2024-01-17 16:51 UTC, Weedshaker commented
you can merge it!... after adjusting the add and remove Event Listener stuff

2024-01-17 22:22 UTC, MrBuggy commented on src/css/variablesCustom.css
> +  --icon-color-blue: #0053A6;
Finde die Farbe leider nirgends in den Repos. Scheint neu zu sein.

2024-01-18 08:16 UTC, Weedshaker approved these changes

2024-01-18 08:23 UTC, merged