MIDUWEB-483: Add 'find abo' case
mits-gossau/web-components-toolbox-klubschule pull request #109
Opened 2024-04-18 07:16 UTC by Nilsilino

2024-04-26 07:49 UTC, Weedshaker approved these changes

2024-04-26 07:49 UTC, Weedshaker commented on src/es/components/molecules/abonnements/Abonnements.js
> +    return this.fetchModules([
do you need all these modules here?

2024-04-26 08:36 UTC, Nilsilino commented on src/es/components/molecules/abonnements/Abonnements.js
> +    return this.fetchModules([
Removed unnecessary Imports

2024-04-29 09:42 UTC, Weedshaker requested changes
Does it work with <button>?
And if yes, does the Abonnements.js style it itself? Then it wouldn't need that import...

2024-04-29 09:42 UTC, Weedshaker commented on src/es/components/molecules/abonnements/Abonnements.js
> +        name: 'a-button'
ks-a-button vs a-button vs button?
siehe Zeile 110

2024-04-29 12:59 UTC, merged