Feature/miduweb 429 standort map
mits-gossau/web-components-toolbox-klubschule pull request #134
Opened 2024-04-30 13:59 UTC by tdesero

2024-05-03 10:10 UTC, Weedshaker requested changes
always remove event listeners at disconnected callback when added at connected callback

2024-05-03 10:10 UTC, Weedshaker commented on src/es/components/molecules/popUpWindow/PopUpWindow.js
> +    this.closeBtn.addEventListener('click', () => {
please, remove the event listener at disconnectedCallback

2024-05-06 07:38 UTC, tdesero commented on src/es/components/molecules/popUpWindow/PopUpWindow.js
> +    this.closeBtn.removeEventListener('click', this.closeListener)
@Weedshaker removed the listener now. Thanks for catching that mistake! :)

2024-05-06 07:57 UTC, Weedshaker approved these changes

2024-05-06 08:42 UTC, merged