Fix/miduweb 1004
mits-gossau/web-components-toolbox-klubschule pull request #236
Opened 2024-06-25 05:06 UTC by MrBuggy

2024-06-25 09:59 UTC, Weedshaker requested changes
adjust to 

previousSibling -> previousElementSibling
nextSibling -> nextElementSibling

and maybe set an extra attribute, so that the heading component can decide by itself to show margin or not.

2024-06-25 09:59 UTC, Weedshaker commented on src/es/components/atoms/spacing/Spacing.js
> +      if (this.previousSibling) this.removeMarginTopBottom(this.previousSibling)
previousSibling -> previousElementSibling
nextSibling -> nextElementSibling
 
Dann gibt es denn error mit setAttribute is not a function error nicht mehr. Die Heading Komponente kann ja auf das style attribute auf Host reagieren, wenn dort margin 0 oder wir setzen zusaetzlich noch ein attribute bsp.: no-margin-top auf die sibling elemente, dann kann jede Komponente selbst dazu reagieren. Denke Heading ist der einzige grosse Sonderfall!?

2024-06-26 06:32 UTC, tdesero approved these changes

2024-06-26 06:32 UTC, tdesero approved these changes

2024-06-26 06:35 UTC, schmidt1024 approved these changes

2024-06-26 06:37 UTC, Weedshaker approved these changes

2024-06-26 06:37 UTC, merged