MIDUWEB-475: Adapted to Data Structure
mits-gossau/web-components-toolbox-klubschule pull request #96
Opened 2024-04-10 17:09 UTC by Nilsilino

2024-04-11 13:36 UTC, Weedshaker approved these changes

2024-04-12 07:47 UTC, Weedshaker submitted a review, later dismissed

2024-04-15 07:18 UTC, schmidt1024 submitted a review, later dismissed
🎉 Nice work!

2024-04-16 11:58 UTC, Weedshaker requested changes
Please, make sure to not undo Changes for example on Event.js. The ks-m-buttons is a new component. Best to first merge master into your branch.

2024-04-16 11:58 UTC, Weedshaker commented on src/es/components/molecules/event/Event.js
> +            ${this.data.buttons ? this.data.buttons.reduce((acc, button, index) => acc + (button.event != "bookmark" ? /* html */ `
this here is a old version... can you first merge master into your branch!? THX

2024-04-16 16:53 UTC, Weedshaker approved these changes

2024-04-17 07:18 UTC, merged